### PR TITLE
Add documentation on custom matchers for specs

### PR DESCRIPTION
**Pull request by forivall**
Fixes https://github.com/atom/docs/issues/143

I tried to match the style of jasmine's documentation on its matchers.

### CODE REVIEW

**Comment by thedaniel** [comment]
Sorry about the delay in reviewing this. The structure of the docs has changed a bit and this doesn't merge cleanly. Would you mind opening it based on the current master? I'll be sure to review & merge in less than "months" ;)

**Comment by forivall** [comment]
Reeee-based. TBH though, I'm more concerned about my open PRs on tree-view and tabs. :smile_cat:

**Comment by thomasjo** [comment]
This looks good to me!

**Comment by thedaniel** [comment]
Thanks!

**Pull request merged**
