### PR TITLE
Add note on how to customize keybindings in editing and deleting section of atom

### PR DESCRIPTION
**Pull request by ungb**
Creating this PR to address https://github.com/atom/atom/issues/4026 

where there's confusion about what keybinding does what and make it more clear in the docs that people can change them to suit their needs.

/cc @nathansobo @rsese

### CODE REVIEW

**Comment by nathansobo** [comment]
Would it be worthwhile to mention word boundaries explicitly since this is a common hangup for people?

**Comment by rsese** [comment]
I think the general note is helpful but since it's a high level note, it seems a little out of place specifically in the "Deleting and Cutting" section?

> Would it be worthwhile to mention word boundaries explicitly since this is a common hangup for people?

I looked at my notes and it seems like we talked about adding docs specifically to address https://github.com/atom/atom/issues/4026?  Would we want to keep the high level note and add more details to address https://github.com/atom/atom/issues/4026, or remove the note and just add a small paragraph to address the issue?

**Comment by nathansobo** [comment]
I'd like to find some place to put an explicit mention of word-based movement and deletion boundaries and give an example of how people might customize them.

**Comment by ungb** [comment]
closing in favor of https://github.com/atom/flight-manual.atom.io/pull/426

**Pull request closed without merging**
