### PR TITLE
Document core URI handler

### PR DESCRIPTION
**Pull request by UziTech**
### Description of the Change

Add documentation for the URI to open files

### Release Notes

Add documentation for the URI to open files

### CODE REVIEW

**Comment by UziTech** [comment]
@atom any feedback?

**Comment by UziTech** [comment]
@sadick254 can this get triaged?

**Review by 50Wliu — APPROVED** [review]

**Comment by 50Wliu** [comment]
No longer comfortable with merging any changes, but this looks fine to me.

**Comment by sadick254** [comment]
Yes @UziTech I will look into it.

**Comment by darangi** [comment]
Thanks for the contribution 🙇🏾‍♂️  @UziTech

**Pull request merged**
