### PR TITLE
Add a clear pathway so people can contribute

### PR DESCRIPTION
**Pull request by briandk**
## Background

Several potential contributors [had trouble finding this repository](https://github.com/atom/flight-manual.atom.io/issues/176).

## What I'm proposing with this PR

- Add a "contribute!" link to the bottom bar of each docs page.
- Add explanatory links to the overview of CONTRIBUTING.md

## This is effectively my first PR on an open-source project

Please be kind O:-)

Add links to help/explanation documents; add link for forking

### CODE REVIEW

**Comment by briandk** [comment]
Eek! I just realized I forgot to do this from a named feature branch. I'm gonna close this, fix that error, and resubmit the PR.

**Comment by gjtorikian** [comment]
I like the text changes in the README to describe contributing. I also _really_ like @lee-dohm's suggestion to simply provide a link to the Edit feature on GitHub: https://github.com/atom/flight-manual.atom.io/issues/176#issuecomment-200502145

Care to make the link behave that way instead? If not, no worries, I'll pick it up. 😁

**Comment by briandk** [comment]
@gjtorikian Let me transition this thread over to my updated PR #181. I wanted to fix the name of my branch.

**Comment by gjtorikian** [comment]
Cool. Closing this out then.

**Pull request closed without merging**
