### PR TITLE
Just updating screenshot for different wording

### PR DESCRIPTION
**Pull request by ItsPugle**
Simply updating the screenshot, as in the current Atom version, the wording is slightly changed.

### CODE REVIEW

**Comment by thomasjo** [comment]
Thanks for helping out! I noticed you're linking to an external image. You're going to have to change the actual image stored in the repo instead of changing the URI.

The screenshot image you'll want to change is the one in the original URI, which you can find at [`content/using-atom/images/menubar.png`](https://github.com/atom/flight-manual.atom.io/blob/master/content/using-atom/images/menubar.png).

**Comment by ItsPugle** [comment]
I spent ages looking for that, but couldn't find it! Guess I wasn't looking hard enough 😄  I've gone ahead and (hopefully) fixed this, now!

**Comment by 50Wliu** [comment]
Can you keep `Stylesheet...` highlighted like it was previously?

**Comment by ItsPugle** [comment]
Done, @50Wliu! How does it look now?

**Comment by thomasjo** [comment]
@ItsPugle Thanks again for helping out, we really appreciate it :bowing_man:

**Comment by ItsPugle** [comment]
Woot woot! Cheers!

**Pull request merged**
