### PR TITLE
Enhance build to process API JSON files for Atom 1.0.0 and newer

### PR DESCRIPTION
**Pull request by jasonrudolph**
This pull request targets the `api-docs` branch. (That branch is currently a work in progress. We anticipate opening a pull request for that branch soon.)

- [x] Pull in the API JSON files for all Atom versions from v1.0.0 to present (6ccef216df76f0c2dc7e0e595b49986706c91618)
- [x] Update Rake task to read from `data/apis-by-version` and not delete source files
- [x] Replace the `split_api_json` Rake task with some equivalent logic in `gulpfile.js`, so that `npm run gulp` continues to provide the end-to-end build process (42c10c6cf57f38bf9a1f109159d53a014b2b65a3)
- [x] Enhance the `nanoc:compile` task in gulp to avoid exceeding the max buffer size, now that our build now writes quite a bit more content to STDOUT

### CODE REVIEW

**Comment by jasonrudolph** [comment]
:wave: @lee-dohm: Here's what I'm working on for the API docs migration so far. If you see anything in here that seems like it's going in a different direction than what you had in mind, please let me know. :bow:

**Comment by lee-dohm** [comment]
Sounds like the right approach to me! 👍

**Comment by jasonrudolph** [comment]
:wave: @lee-dohm: I think this is ready for review now. 

Note that the [build currently fails when attempting to verify external links](https://travis-ci.org/atom/flight-manual.atom.io/builds/551075675#L7135), but I anticipate us fixing that issue before we merge these changes into `master`. (This pull request targets the `api-docs` branch, so merging this pull request will not merge these changes to the `master` branch.)

**Comment by jasonrudolph** [comment]
:wave: @lee-dohm: I'm gonna go ahead and merge this branch, so that @as-cii and I can get started on the next steps. However, if you notice anything that you'd like to see changed, just let me know, and I'll be sure to take a look.

**Pull request merged**
