### PR TITLE
Fix Red Hat install product names

### PR DESCRIPTION
**Pull request by lucascosti**
'RedHat' -> 'Red Hat' and other minor fixes.

### CODE REVIEW

**Comment by lee-dohm** [comment]
Thanks for contributing :grinning:

**Comment by lucascosti** [comment]
My pleasure, @lee-dohm 😃 . Thanks a lot for this feature, there are a lot of people in the docs team here at Red Hat that will actually have their installs up-to-date from now on! 🎉

**Comment by lee-dohm** [comment]
You're most welcome @lucascosti. I'm sure @daviwil will be happy to hear that you're enjoying it :grinning:

**Comment by daviwil** [comment]
That's awesome news, thanks for letting us know!

**Pull request merged**
