### PR TITLE
Add keyboard shortcuts for Linux and Windows

### PR DESCRIPTION
**Pull request by mlalkaka**
This change updates the keyboard shortcuts in Chapters 1 and a lot of Chapter 2 so that they apply to Linux and Windows users as well. Issue https://github.com/atom/docs/issues/16 (Enhanced keymap support) is probably the ideal solution for this problem, but this change at least assists Linux and Windows users get started with Atom for now.

### CODE REVIEW

**Comment by mlalkaka** [comment]
Hi, any feedback for this change? Was there a process I was supposed to follow before submitting this PR?

**Comment by thedaniel** [comment]
Sorry about leaving this for so long, unfortunately master has changed quite a bit since this was opened and it no longer merges cleanly. You did everything right, we just have more open PRs than we can review in a timely fashion sometimes. I'm generally in favor of adding cross-platform key shortcuts to the docs, if you want to reopen a PR with similar changes against the current docs, I'll make a point to review it.

**Comment by lee-dohm** [comment]
Thanks very much for the effort you put into this @mlalkaka. I'm sorry that this got dropped on the floor. I hope that the new platform-specific content support helps with some of what you wanted to see in the Flight Manual.

**Comment by mlalkaka** [comment]
It's alright @thedaniel and @lee-dohm. I still learned a few things along the way. Thanks for introducing the platform-specific content @lee-dohm; based on my experience learning Atom on Windows, I'm sure it will help others get started with Atom!

**Pull request closed without merging**
