### PR TITLE
Update find-and-replace.md

### PR DESCRIPTION
**Pull request by seranki**
Proposed adding this note at the end of line 15:
"Note: In the replacement part of a regex the syntax $1, $2, … $& must be used."
My "regex" experience is with languages that use the \1, \2 syntax, so the need to use Javascript syntax was not obvious to me.
Regards.

### CODE REVIEW

**Comment by lee-dohm** [comment]
Thanks for the contribution.

This would be better as a [Note admonition block](https://github.com/atom/flight-manual.atom.io/blob/master/CONTRIBUTING.md#admonition-blocks).

**Comment by seranki** [comment]
I edited the pull request per your recommendation to make it a Note admonition block. I also moved it one para down where I think it fits better.
Since I am not a GitHub expert, please feel free to tell me how to correct any errors in how I did it.
Thanks.

**Comment by lee-dohm** [comment]
Thanks for this!

**Comment by seranki** [comment]
Thanks for your help. I will delete the branch now.

**Pull request merged**
